Intro to TENSORFLOW

In [ ]:
#import tensorflow

import tensorflow as tf
print(tf.__version__)

2.19.0


In [ ]:
#create tensor with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
#check the no. of dimensions of a tensor(ndim)
scalar.ndim

0

In [ ]:
#crreate a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
vector.ndim

1

In [ ]:
#matrix
matrix = tf.constant([[5,6],[7,8]])
print(matrix)
print(matrix.ndim)
print(matrix.shape)
print(matrix[1])

tf.Tensor(
[[5 6]
 [7 8]], shape=(2, 2), dtype=int32)
2
(2, 2)
tf.Tensor([7 8], shape=(2,), dtype=int32)


In [ ]:
another_mat = tf.constant([[10.,7.],
                           [3.,2.],
                           [08.,16.]], dtype=tf.float16)
another_mat


<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8., 16.]], dtype=float16)>

In [ ]:
another_mat.ndim

2

In [ ]:
#create a TENSOR
ten = tf.constant([[[1,2,3],[5,6,7],
                    [8,9,0],[5,7,9]],
                     [[11,12,13],[4,5,6],
                      [1,2,5],[16,8,3]]])

print(ten)
print(ten.ndim)
print(ten.shape)

tf.Tensor(
[[[ 1  2  3]
  [ 5  6  7]
  [ 8  9  0]
  [ 5  7  9]]

 [[11 12 13]
  [ 4  5  6]
  [ 1  2  5]
  [16  8  3]]], shape=(2, 4, 3), dtype=int32)
3
(2, 4, 3)


In [ ]:
tf.Variable

tensorflow.python.ops.variables.Variable

In [ ]:
#creating tensors with tf.Variable
changeable_tensor = tf.Variable([20,7,3])
unchangeable_tensor = tf.constant([20,7,1])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([20,  7,  3], dtype=int32)>,
 <tf.Tensor: shape=(3,), dtype=int32, numpy=array([20,  7,  1], dtype=int32)>)

In [ ]:
changeable_tensor[0]=7
changeable_tensor

TypeError: 'ResourceVariable' object does not support item assignment

In [ ]:
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([7, 7, 3], dtype=int32)>

In [ ]:
unchangeable_tensor[0].assign(9)
unchangeable_tensor

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

In [ ]:
#creating random tensors
rt = tf.random.Generator.from_seed(4) #set seed for reproduciblity
rt = rt.normal(shape=(3,2))
rt
rt2 = tf.random.Generator.from_seed(4)
rt2 = rt2.normal(shape=(3,2))

rt,rt2= rt,rt2
rt,rt2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 1.0019137 ,  0.6735137 ],
        [ 0.06987712, -1.4077919 ],
        [ 1.0278524 ,  0.27974114]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 1.0019137 ,  0.6735137 ],
        [ 0.06987712, -1.4077919 ],
        [ 1.0278524 ,  0.27974114]], dtype=float32)>)

shuffle the order of elements in a tensor

In [ ]:
#shuffle the tensor
not_shuffle = tf.constant([[10,7],
                           [5,6],
                           [4,16]])
not_shuffle

#shuffle our non-shuffle
a =tf.random.shuffle(not_shuffle)
a

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 4, 16],
       [ 5,  6],
       [10,  7]], dtype=int32)>

In [ ]:
a =tf.random.shuffle(not_shuffle, seed=45)
a

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 5,  6],
       [10,  7],
       [ 4, 16]], dtype=int32)>

In [ ]:
b = tf.random.set_seed(45) #global level seed
a = tf.random.shuffle(not_shuffle, seed=45) #operation level seed
b, a

(None,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 5,  6],
        [ 4, 16]], dtype=int32)>)

other ways to create tensor using NUMPY

In [ ]:
# create a tensor of all ones
tf.ones([2,3])

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [ ]:
#create a tensor of all zeros
tf.zeros([2,3])

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

Turn Numpy into tensors

In [ ]:
import numpy as np
n = np.arange(1,25)
n

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [ ]:
t = tf.constant(n, shape=(2,3,4))
t

<tf.Tensor: shape=(2, 3, 4), dtype=int64, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])>

Getting info from tensors

In [ ]:
 #create a rank 3 dimensions
a = tf.zeros(shape=(2,2,3,4))
a

<tf.Tensor: shape=(2, 2, 3, 4), dtype=float32, numpy=
array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]],


       [[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
a.shape, a.ndim, tf.size(a)

(TensorShape([2, 2, 3, 4]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=48>)

In [ ]:
2*2*3*4

48

In [ ]:
print("Datatype of every element:", a.dtype)
print("Number of dimensions (rank):", a.ndim)
print("Shape of tensor:", a.shape)
print("Elements along axis 0 of tensor:", a.shape[0])
print("Elements along the last axis of tensor:", a.shape[-1])
print("Total number of elements (2*2*3*4):", tf.size(a).numpy)
print("Total number of elements (2*2*3*4):", tf.size(a))
print("Tensor as NumPy array:", a.numpy())
print("Tensor as NumPy array:", np.array(a))

Datatype of every element: <dtype: 'float32'>
Number of dimensions (rank): 4
Shape of tensor: (2, 2, 3, 4)
Elements along axis 0 of tensor: 2
Elements along the last axis of tensor: 4
Total number of elements (2*2*3*4): <bound method _EagerTensorBase.numpy of <tf.Tensor: shape=(), dtype=int32, numpy=48>>
Total number of elements (2*2*3*4): tf.Tensor(48, shape=(), dtype=int32)
Tensor as NumPy array: [[[[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]

  [[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]]


 [[[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]

  [[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]]]
Tensor as NumPy array: [[[[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]

  [[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]]


 [[[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]

  [[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]]]


Indexing Tensors

In [ ]:
list = [1,4,6,5,9]
list[:3]

[1, 4, 6]

In [ ]:
a[:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 4), dtype=float32, numpy=
array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]]],


       [[[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
a[:2,:2,:,:2]

<tf.Tensor: shape=(2, 2, 3, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
a1 = tf.constant([[16,8],
                  [3,4]])
a1.shape, a1.ndim, a1.dtype

(TensorShape([2, 2]), 2, tf.int32)

In [ ]:
list, list[-1]

([1, 4, 6, 5, 9], 9)

In [ ]:
#alternative to tf.newaxis
tf.expand_dims(a1, axis=-1)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[16],
        [ 8]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [ ]:
tf.expand_dims(a1, axis=0)

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[16,  8],
        [ 3,  4]]], dtype=int32)>

Manipulating tensors(tensor operations)

In [ ]:
#basic operations +,-,*,/
#you can add values to a tensor using this operator
a = tf.constant([8,16,3])
print(a+10)
print(a-5)
print(a*5)
print(a/2)


tf.Tensor([18 26 13], shape=(3,), dtype=int32)
tf.Tensor([ 3 11 -2], shape=(3,), dtype=int32)
tf.Tensor([40 80 15], shape=(3,), dtype=int32)
tf.Tensor([4.  8.  1.5], shape=(3,), dtype=float64)


In [ ]:
b= tf.multiply(a, 8)
b

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 64, 128,  24], dtype=int32)>

Matrix Multiplication (tf.linalg.matmul)

In [ ]:
a*a

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 64, 256,   9], dtype=int32)>

In [ ]:
c = tf.constant([[1,2],
                 [5,6],
                 [4,5]
                 ])
d = tf.constant([[1,2,3],
                 [4,5,6]])
c,d

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [5, 6],
        [4, 5]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>)

In [ ]:
c*d #inner number must match like (2,3),(3,2)

InvalidArgumentError: {{function_node __wrapped__Mul_device_/job:localhost/replica:0/task:0/device:CPU:0}} Incompatible shapes: [3,2] vs. [2,3] [Op:Mul] name: 

In [ ]:
c = tf.constant([[1,2],
                 [4,5],
                 [5,6]])
d = tf.constant([[1,2,3],
                 [4,5,6]])
tf.matmul(c,d)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 9, 12, 15],
       [24, 33, 42],
       [29, 40, 51]], dtype=int32)>

In [ ]:
#reshaping the tensor
tf.reshape(c, shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 5],
       [6, 4, 5]], dtype=int32)>

In [ ]:
tf.transpose(c)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 4, 5],
       [2, 5, 6]], dtype=int32)>

In [ ]:
#using tensordot product, matmul
tf.tensordot(tf.transpose(c), d, axes=1)

In [ ]:
tf.matmul(c, tf.reshape(d, shape=(2,3)))

changing the datatype of a tensor

In [ ]:
# create a tensor with default datatype
a = tf.constant([1,3,5])
a.dtype

tf.int32

In [ ]:
b = tf.constant([1.2,3.4,5.6])
b.dtype

tf.float32

In [ ]:
#change from float32 to float16
b = tf.cast(a, dtype=tf.float16)
b.dtype
#

tf.float16

In [ ]:
#change from int32 to float32
b = tf.cast(b, dtype=tf.float16)
b.dtype

tf.float16

Aggregating tensor => considering them from multiple values down to a smaller amt of values.

In [ ]:
a = tf.constant([-1, -3, -5]) #-ve values into +ve
a.dtype, a

(tf.int32,
 <tf.Tensor: shape=(3,), dtype=int32, numpy=array([-1, -3, -5], dtype=int32)>)

In [ ]:
tf.abs(a)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 3, 5], dtype=int32)>

Forms of aggregation

In [ ]:
# get the minimum, maximum, mean, sum
a = tf.constant(np.random.randint(0,100, size=50))
a


<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([98, 17,  8, 33, 10, 62, 40, 17, 26, 72, 89, 55, 50, 20, 72,  0, 74,
       43, 77, 77, 75, 54,  4,  3, 88, 91, 12, 37, 23, 82, 28, 45, 10, 34,
       22, 90, 88, 34, 81, 31,  6, 13, 64, 47, 90, 30, 34, 81, 93, 52])>

In [ ]:
tf.size(a), a.shape, a.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [ ]:
# find the minimum, max, mean, sum
tf.reduce_min(a)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [ ]:
tf.reduce_max(a)

<tf.Tensor: shape=(), dtype=int64, numpy=98>

In [ ]:
tf.reduce_mean(a)


<tf.Tensor: shape=(), dtype=int64, numpy=47>

In [ ]:
tf.stats.reduce_sum(a)


<tf.Tensor: shape=(), dtype=int64, numpy=2382>

In [ ]:
#we need variance so use tensorflow probability
# find the variance
import tensorflow_probability as tfp
tfp.stats.variance(a)

<tf.Tensor: shape=(), dtype=int64, numpy=890>

In [ ]:
# find the standard deviance
tf.math.reduce_std(tf.cast(a, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=29.826671600341797>

In [ ]:
tf.math.reduce_variance(tf.cast(a, dtype=tf.float32))


<tf.Tensor: shape=(), dtype=float32, numpy=889.63037109375>

In [ ]:
# find the positional max, min
tf.random.set_seed(42)
m  = tf.random.uniform(shape=[50])
m

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [ ]:
tf.argmax(m)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [ ]:
m[tf.argmax(m)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.967138409614563>

In [ ]:
# check for equality
m[tf.argmax(m)] == tf.reduce_max(m)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [ ]:
# find the  positional minimum
tf.argmin(m)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [ ]:
m[tf.argmin(m)] == tf.reduce_min(m)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

Squeezing tensor (removing all single dimensions)

In [ ]:
tf.random.set_seed(42)
g = tf.constant(tf.random.uniform(shape= [50]), shape=(1,1,1,50))
g


<tf.Tensor: shape=(1, 1, 1, 50), dtype=float32, numpy=
array([[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
          0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
          0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
          0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
          0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
          0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
          0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
          0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
          0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
          0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]],
      dtype=float32)>

In [ ]:
g.shape

TensorShape([1, 1, 1, 50])

In [ ]:
g_squeeze = tf.squeeze(g)
g_squeeze, g_squeeze.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>,
 TensorShape([50]))

One-hot encoding

In [ ]:
# create a list of indices

list = [0,1,2,3]
tf.one_hot(list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [ ]:
# specify custom values for one hot encoding
tf.one_hot(list, depth=4, on_value="yes", off_value="no")


<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'yes', b'no', b'no', b'no'],
       [b'no', b'yes', b'no', b'no'],
       [b'no', b'no', b'yes', b'no'],
       [b'no', b'no', b'no', b'yes']], dtype=object)>

squaring , log, square root

In [ ]:
b = tf.range(1,10)
b

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [ ]:
tf.square(b)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [ ]:
tf.sqrt(b) #error code

In [ ]:
tf.sqrt(tf.cast(b, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [ ]:
tf.math.log(tf.cast(b, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

Tensors and NumPy

In [ ]:
n =tf.constant(np.array([3.,7.,5.,10]))
n

<tf.Tensor: shape=(4,), dtype=float64, numpy=array([ 3.,  7.,  5., 10.])>

In [ ]:
np.array(n), type(np.array(n)) #covert our tensor to numpy

(array([ 3.,  7.,  5., 10.]), numpy.ndarray)

In [ ]:
# convert tensor n to numpy
n.numpy(), type(n.numpy())

(array([ 3.,  7.,  5., 10.]), numpy.ndarray)

In [ ]:
m=tf.constant([7.])
m.numpy()[0]

np.float32(7.0)

In [ ]:
#the default types of each are slightly different
numpy_j = tf.constant(np.array([3.,7.,10.]))
tensor_j = tf.constant([3.,7.,10.])
#check the datatypes
numpy_j.dtype, tensor_j.dtype

(tf.float64, tf.float32)